# Generated by Django 2.2.1 on 2019-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=255, verbose_name='公司简称')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户管理',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=255, verbose_name='公司简称')),
                ('account', models.CharField(max_length=500, verbose_name='银行账号')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商管理',
            },
        ),
    ]
