# Generated by Django 2.2.1 on 2019-05-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('short_name', models.CharField(max_length=255, verbose_name='公司简称')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Company')),
            ],
            bases=('company.company',),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Company')),
                ('account', models.CharField(max_length=500, verbose_name='银行账号')),
            ],
            bases=('company.company',),
        ),
    ]
