# Generated by Django 2.2.1 on 2019-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
                ('mobile', models.CharField(max_length=60, verbose_name='手机')),
            ],
        ),
    ]
