# Generated by Django 2.2.1 on 2019-05-30 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='订单号')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Customer', verbose_name='客户')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.Supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
