# Generated by Django 2.2.1 on 2019-05-30 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100, verbose_name='订单号')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Customer', verbose_name='客户')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Supplier', verbose_name='供应商')),
            ],
        ),
    ]
